---
title: "plot_pca.Rmd"
author: "Andrea Estandia"
date: "21/01/2024"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/great-tit-genomics_source.R")
```


```{r}
pca <- 
  read.table(file.path(data_path,
                             "plink",
                             "10K_processed", 
                             "10K_pca.eigenvec"),
                    header=F) 

colnames(pca) <- c("dataset", "bto_ring", paste0("PC", seq(1:(dim(pca)[2]-2))))
```

```{r}
immigrant_resident <- read.csv(file.path(data_path,
                                          "dfs_derived",
                                          "immigrants_residents_10K.csv"))
#Nestbox where they've bred
nb <- read.csv(file.path(data_path,
                         "wytham_ringing_breeding",
                         "Nest_box_habitat_data.csv")) %>%
  as_tibble()

df <- pca %>% 
  left_join(immigrant_resident) %>% 
  left_join(nb) 
```


Wytham map
```{r}
shape <- 
  read_sf(dsn = file.path(data_path,
                                 "wytham_map",
                                 "perimeter.shp"))

df_noNA <- df %>% 
  drop_na(x, y)

df_sf <- st_as_sf(df_noNA, coords = c("x", "y"), crs = st_crs(shape))

```


```{r}
pal <- wesanderson::wes_palette("Zissou1", 5, type = "continuous")
```

PC1 and PC2 plots across space  
```{r}
p1 = df_sf %>%
  ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(data = df_sf, aes(color = PC1), size = 2) +
  scale_color_gradientn(colours = pal, name = "PC1") +
    labs(title = "All individuals - PC1", subtitle = NULL, x = "", y = "") +
    theme_minimal() +
  theme(
    panel.background = element_rect(fill = "#f2f2f2", color = NA),  
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),  
    axis.ticks = element_line(color = "black"), 
    text = element_text(family = "roboto_condensed"),
    legend.position = "bottom"
  )

p2 = ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(data = df_sf, aes(color = PC2), size = 2) +
  scale_color_gradientn(colours = pal) +
    labs(title = "All individuals - PC2", subtitle = NULL, x = "", y = "") +
    theme_minimal() +
  theme(
    panel.background = element_rect(fill = "#f2f2f2", color = NA),  
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),  
    axis.ticks = element_line(color = "black"), 
    text = element_text(family = "roboto_condensed"),
    legend.position = "bottom"
  )

p3 = df_sf %>%
  filter(imm_res == "resident") %>%
  ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(aes(color = PC1), size = 2) +  
    scale_color_gradientn(colours = pal) +
    #scale_color_viridis_c(name = "PC1", option = "viridis") +
    labs(title = NULL, subtitle = NULL, x = "\nEasting\n", y = "\nNorthing\n") +
    theme_minimal() +
    theme(
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      text = element_text(family = "Calibri"),
      axis.title = element_text(family = "Calibri"),
      legend.position = "bottom"
    )+
  labs(title="Residents - Breeding box")

p4 = df_sf %>%
  filter(imm_res != "residents") %>%
  ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(aes(color = PC1), size = 2) +  
    #scale_color_viridis_c(name = "PC1", option = "viridis") +
    scale_color_gradientn(colours = pal) +
    labs(title = NULL, subtitle = NULL, x = "\nEasting\n", y = "\nNorthing\n") +
    theme_minimal() +
    theme(
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      text = element_text(family = "Calibri"),
      axis.title = element_text(family = "Calibri"),
      legend.position = "bottom"
    )+
  labs(title="Immigrants - Breeding box")



resident_plot <- p3 + p4 + plot_layout(guides = "collect")


ggsave(resident_plot,
       filename = file.path(figures_path,
                 "resident_immigrant_pca.pdf"), 
       device = "pdf",
       width = 12, 
       height = 6, 
       units = "in")

ggsave(immigrant_plot,
       filename = file.path(figures_path,
                 "immigrant_plot.pdf"), 
       device = "pdf",
       width = 12, 
       height = 6, 
       units = "in")

```


PC1 by year
```{r}
p1_yr <- 
  df_sf %>%
  filter(yr %in% c("2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010")) %>%
  ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(aes(color = PC1), size = 2) +
  scale_color_gradientn(colours = pal, name = "PC1") +
  labs(
    title = "PC1 by Year (2008–2010)",
    x = "", y = ""
  ) +
  facet_wrap(~ yr) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "#f2f2f2", color = NA),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    text = element_text(family = "roboto_condensed"),
    legend.position = "bottom"
  )

ggsave(p1_yr,
       filename = file.path(figures_path,
                 "pc1_by_year.pdf"), 
       device = "pdf",
       width = 16, 
       height = 8, 
       units = "in")
```
